"""
Generate the 01_Data_Understanding_and_Cleaning.ipynb notebook.
This script builds the notebook JSON programmatically to avoid
hand-editing the .ipynb format.
"""
import json

def md(source_lines):
    """Create a markdown cell."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source_lines
    }

def code(source_lines):
    """Create a code cell."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines
    }

cells = []

# ============================================================
# TITLE
# ============================================================
cells.append(md([
    "# 🌱 HydroGrow AI — Phase 1: Data Understanding & Cleaning\n",
    "\n",
    "---\n",
    "\n",
    "**Full Title:** HydroGrow AI: An Intelligent Decision Support System for Hydroponic Lettuce Growth Prediction, Disease Prevention and Growth Optimization\n",
    "\n",
    "**Notebook:** `01_Data_Understanding_and_Cleaning.ipynb`  \n",
    "**Author:** HydroGrow AI Team  \n",
    "**Date:** 2026-07-15  \n",
    "**Version:** 1.0\n",
    "\n",
    "---"
]))

# ============================================================
# SECTION 1 - Project Introduction
# ============================================================
cells.append(md([
    "## 1 · Project Introduction\n",
    "\n",
    "### 1.1 Objective\n",
    "\n",
    "HydroGrow AI is designed to become a production-grade **AI-powered Hydroponic Assistant** capable of:\n",
    "\n",
    "| Capability | Status |\n",
    "|---|---|\n",
    "| Understanding hydroponic lettuce data | 🔄 Phase 1 (this notebook) |\n",
    "| Predicting plant growth | 📋 Planned |\n",
    "| Predicting plant requirements | 📋 Planned |\n",
    "| Supporting disease prevention | 📋 Planned |\n",
    "| Providing intelligent recommendations | 📋 Planned |\n",
    "| Machine Learning integration | 📋 Planned |\n",
    "| ChatGPT-like web application | 📋 Planned |\n",
    "\n",
    "**This notebook focuses exclusively on Phase 1**: data understanding, quality assessment, and safe cleaning.\n",
    "\n",
    "### 1.2 Dataset Overview\n",
    "\n",
    "Three independent hydroponic lettuce experiments are available, each stored as an Excel workbook containing multiple sheets:\n",
    "\n",
    "| Dataset | Description |\n",
    "|---|---|\n",
    "| **Experiment 1** | Environmental conditions & plant measurements (6 sheets) |\n",
    "| **Experiment 2** | Environmental conditions & plant measurements (7 sheets) |\n",
    "| **Experiment 3** | Environmental conditions & plant measurements (5 sheets) |\n",
    "\n",
    "Each workbook typically contains sheets for:\n",
    "- **Seedlings measurements** — baseline plant biometrics at transplant\n",
    "- **Water quality (Sensor)** — continuous pH, EC, TDS, temperature, humidity, CO₂\n",
    "- **Water quality (Portable)** — manual spot-check measurements across replicates\n",
    "- **Nutrients & Water consumptions** — nutrient dosing and water usage logs\n",
    "- **Harvest measurements** — final harvest biometrics per replicate/treatment\n",
    "- Additional sheets (Head diameter, Taste tests, Survey forms) in some experiments\n",
    "\n",
    "### 1.3 Expected Workflow\n",
    "\n",
    "```\n",
    "Phase 1 (This Notebook)\n",
    "├── Load all raw datasets\n",
    "├── Understand structure & semantics\n",
    "├── Assess data quality comprehensively\n",
    "├── Apply only safe, reversible cleaning\n",
    "├── Validate cleaning outcomes\n",
    "├── Generate data dictionary\n",
    "└── Save cleaned datasets → data/processed/\n",
    "```\n",
    "\n",
    "> ⚠️ **Guiding Principle:** We never delete rows due to outliers, never invent missing values, and never remove suspicious values. If something looks questionable, we **flag it** and document it for expert review."
]))

# ============================================================
# SECTION 2 - Import Libraries
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 2 · Import Libraries"
]))

cells.append(code([
    '"""\n',
    "Import only the libraries required for Phase 1.\n",
    "No ML / DL / visualization-heavy imports at this stage.\n",
    '"""\n',
    "\n",
    "import os\n",
    "import sys\n",
    "import logging\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "from typing import Dict, List, Tuple, Optional, Any\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from IPython.display import display, Markdown, HTML\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Configuration\n",
    "# ---------------------------------------------------------------------------\n",
    'warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")\n',
    'pd.set_option("display.max_columns", 60)\n',
    'pd.set_option("display.max_rows", 100)\n',
    'pd.set_option("display.max_colwidth", 40)\n',
    'pd.set_option("display.float_format", "{:.4f}".format)\n',
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Logging — gives us a persistent audit trail inside the notebook\n",
    "# ---------------------------------------------------------------------------\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    '    format="%(asctime)s | %(levelname)-8s | %(message)s",\n',
    '    datefmt="%H:%M:%S",\n',
    ")\n",
    'logger = logging.getLogger("HydroGrow")\n',
    'logger.info("Libraries imported successfully.")\n',
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Project paths (relative — never hardcoded absolutes)\n",
    "# ---------------------------------------------------------------------------\n",
    "PROJECT_ROOT = Path(os.getcwd()).parent  # notebooks/ → project root\n",
    'RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"\n',
    'PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"\n',
    "PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    'logger.info(f"Project root : {PROJECT_ROOT}")\n',
    'logger.info(f"Raw data dir : {RAW_DATA_DIR}")\n',
    'logger.info(f"Processed dir: {PROCESSED_DATA_DIR}")\n',
    "\n",
    'print(f"\\n✅ Python {sys.version}")\n',
    'print(f"✅ pandas {pd.__version__}  |  numpy {np.__version__}")'
]))

# ============================================================
# SECTION 3 - Load Data
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 3 · Load Data\n",
    "\n",
    "Each experiment workbook contains **multiple sheets** with different structures (multi-row headers, merged cells, sub-tables). We load every sheet of every workbook into a structured dictionary so no information is lost."
]))

cells.append(code([
    "def discover_excel_files(directory: Path) -> List[Path]:\n",
    '    """Discover all .xlsx files in the given directory (non-recursive)."""\n',
    '    files = sorted(directory.glob("*.xlsx"))\n',
    "    if not files:\n",
    '        raise FileNotFoundError(f"No .xlsx files found in {directory}")\n',
    '    logger.info(f"Discovered {len(files)} Excel file(s) in {directory}")\n',
    "    return files\n",
    "\n",
    "\n",
    "def load_all_sheets(filepath: Path) -> Dict[str, pd.DataFrame]:\n",
    '    """\n',
    "    Load every sheet from an Excel workbook using `header=None`\n",
    "    so we preserve the raw structure including multi-row headers.\n",
    "    Returns a dict mapping sheet_name -> DataFrame.\n",
    '    """\n',
    "    xl = pd.ExcelFile(filepath)\n",
    "    sheets = {}\n",
    "    for name in xl.sheet_names:\n",
    "        sheets[name] = pd.read_excel(filepath, sheet_name=name, header=None)\n",
    "        logger.info(\n",
    '            f"  └─ Sheet \'{name}\': {sheets[name].shape[0]:,} rows × {sheets[name].shape[1]} cols"\n',
    "        )\n",
    "    return sheets\n",
    "\n",
    "\n",
    "# ---- Discover and load ----\n",
    "excel_files = discover_excel_files(RAW_DATA_DIR)\n",
    "\n",
    "# Store everything in an ordered dict: experiment label -> {sheet_name: df}\n",
    "experiments_raw: Dict[str, Dict[str, pd.DataFrame]] = {}\n",
    "\n",
    "for idx, fpath in enumerate(excel_files, start=1):\n",
    '    label = f"Experiment {idx}"\n',
    '    logger.info(f"Loading {label}: {fpath.name}")\n',
    "    experiments_raw[label] = load_all_sheets(fpath)\n",
    "\n",
    'print("\\n" + "=" * 70)\n',
    'print("LOADING SUMMARY")\n',
    'print("=" * 70)\n',
    "for exp_label, sheets in experiments_raw.items():\n",
    "    total_rows = sum(df.shape[0] for df in sheets.values())\n",
    '    print(f"\\n📂 {exp_label}  ({len(sheets)} sheets, {total_rows:,} total rows)")\n',
    "    for sname, df in sheets.items():\n",
    '        print(f"   ├─ {sname:<45s}  {df.shape[0]:>5,} rows × {df.shape[1]:>3} cols")'
]))

cells.append(md([
    "### 3.1 Parse Sheets into Clean DataFrames\n",
    "\n",
    "The raw Excel sheets use **multi-row headers**, **merged cells**, and **sub-tables** side-by-side. Below we parse each sheet type into properly-headed DataFrames using dedicated parser functions.\n",
    "\n",
    "> We apply **minimal parsing only** — setting correct headers and stripping structural artifacts. No data values are modified."
]))

# ---- Sheet Parsers ----
cells.append(code([
    "# ==========================================================================\n",
    "# Sheet Parsers — one per sheet type\n",
    "# ==========================================================================\n",
    "\n",
    "def safe_str_row(series: pd.Series) -> list:\n",
    '    """\n',
    "    Convert a pandas Series (row) into a list of clean Python strings.\n",
    "    Handles pandas 3.x nullable string dtype where .astype(str)\n",
    "    preserves NaN as float('nan') instead of the string 'nan'.\n",
    "    Returns '' for any missing/NaN/NaT values.\n",
    '    """\n',
    '    return [str(v).strip() if pd.notna(v) else "" for v in series]\n',
    "\n",
    "\n",
    "def parse_seedlings(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """\n',
    "    Parse the Seedlings measurements sheet.\n",
    "    Row 0 is a title row; Row 1 contains column headers; Data starts at Row 2.\n",
    '    """\n',
    "    headers = safe_str_row(df_raw.iloc[1])\n",
    "    data = df_raw.iloc[2:].copy()\n",
    "    data.columns = headers\n",
    "    data = data.reset_index(drop=True)\n",
    '    data.insert(0, "experiment", exp_label)\n',
    "    return data\n",
    "\n",
    "\n",
    "def parse_sensor_water_quality(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """\n',
    "    Parse the Water quality measurements (Sensor) sheet.\n",
    "    Row 0: replicate label; Row 1: column headers.\n",
    "    Columns 0-5: Water quality; Columns 6-10: Air parameters.\n",
    "    Data starts at Row 2.\n",
    '    """\n',
    "    # Extract replicate label from row 0 (e.g., 'Replicate 1 T1')\n",
    '    replicate_label = str(df_raw.iloc[0, 2]).strip() if pd.notna(df_raw.iloc[0, 2]) else "Unknown"\n',
    "\n",
    "    headers = safe_str_row(df_raw.iloc[1])\n",
    "    data = df_raw.iloc[2:].copy()\n",
    "    data.columns = headers\n",
    "    data = data.reset_index(drop=True)\n",
    '    data.insert(0, "replicate", replicate_label)\n',
    '    data.insert(0, "experiment", exp_label)\n',
    "\n",
    "    # The sheet has two Date/Time column pairs (water + air)\n",
    "    # Rename to disambiguate\n",
    "    cols = list(data.columns)\n",
    "    seen = {}\n",
    "    new_cols = []\n",
    "    for c in cols:\n",
    "        if c in seen:\n",
    "            seen[c] += 1\n",
    '            new_cols.append(f"{c}_{seen[c]}")\n',
    "        else:\n",
    "            seen[c] = 0\n",
    "            new_cols.append(c)\n",
    "    data.columns = new_cols\n",
    "    return data\n",
    "\n",
    "\n",
    "def parse_portable_water_quality(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """\n',
    "    Parse the Water quality parameters (Portable) sheet.\n",
    "    This has a complex 3-row header: Row 0 = time slots & air params,\n",
    "    Row 1 = replicate labels, Row 2 = measurement names.\n",
    "    Data starts at Row 3.\n",
    '    """\n',
    "    row0 = safe_str_row(df_raw.iloc[0])\n",
    "    row1 = safe_str_row(df_raw.iloc[1])\n",
    "    row2 = safe_str_row(df_raw.iloc[2])\n",
    "\n",
    "    # Build composite column names: {time}_{replicate}_{measurement}\n",
    "    composite_cols = []\n",
    '    current_time = "unknown"\n',
    '    current_replicate = "unknown"\n',
    "\n",
    "    for i in range(len(row0)):\n",
    "        r0 = row0[i]\n",
    "        r1 = row1[i]\n",
    "        r2 = row2[i]\n",
    "\n",
    '        if r0 and r0 not in ("nan", "NaT") and "Air" not in r0 and "Date" not in r0:\n',
    '            current_time = r0.replace(":", "")\n',
    '        if r0 in ("Date", "Date "):\n',
    '            current_time = "date"\n',
    '        if r0 and "Air" in r0:\n',
    '            current_replicate = "Air"\n',
    "\n",
    '        if r1 and r1 not in ("nan", "NaT") and (not r0 or "Air" not in r0):\n',
    '            current_replicate = r1.replace(" ", "_")\n',
    "\n",
    '        if r2 and r2 not in ("nan", "NaT"):\n',
    "            measurement = r2\n",
    "        else:\n",
    '            measurement = r0 if (r0 and r0 not in ("nan", "NaT")) else f"col_{i}"\n',
    "\n",
    '        if current_time == "date":\n',
    '            col_name = "date"\n',
    '        elif current_replicate == "Air":\n',
    '            col_name = f"{current_time}_air_{measurement}"\n',
    "        else:\n",
    '            col_name = f"{current_time}_{current_replicate}_{measurement}"\n',
    "\n",
    "        composite_cols.append(col_name)\n",
    "\n",
    "    # Ensure uniqueness\n",
    "    seen = {}\n",
    "    unique_cols = []\n",
    "    for c in composite_cols:\n",
    '        c_clean = c.replace(" ", "_").replace(".", "").lower()\n',
    "        if c_clean in seen:\n",
    "            seen[c_clean] += 1\n",
    '            unique_cols.append(f"{c_clean}_{seen[c_clean]}")\n',
    "        else:\n",
    "            seen[c_clean] = 0\n",
    "            unique_cols.append(c_clean)\n",
    "\n",
    "    data = df_raw.iloc[3:].copy()\n",
    "    data.columns = unique_cols\n",
    "    data = data.reset_index(drop=True)\n",
    '    data.insert(0, "experiment", exp_label)\n',
    "    return data\n",
    "\n",
    "\n",
    "def parse_nutrients_water(df_raw: pd.DataFrame, exp_label: str) -> Dict[str, pd.DataFrame]:\n",
    '    """\n',
    "    Parse the Nutrients & Water consumptions sheet.\n",
    "    Contains 2 or 3 side-by-side sub-tables separated by blank columns.\n",
    "    Returns a dict of parsed sub-tables.\n",
    '    """\n',
    "    row0 = df_raw.iloc[0]\n",
    "\n",
    "    # Find sub-table boundaries from row 0 headers\n",
    "    sub_tables = {}\n",
    "    current_label = None\n",
    "    start_col = None\n",
    "\n",
    "    for i, val in enumerate(row0):\n",
    '        val_str = str(val).strip() if pd.notna(val) else ""\n',
    '        if val_str and val_str not in ("nan", "NaT"):\n',
    "            # Close previous sub-table\n",
    "            if current_label is not None:\n",
    "                sub_tables[current_label] = (start_col, i - 1)\n",
    "            current_label = val_str\n",
    "            start_col = i\n",
    "    # Close last sub-table\n",
    "    if current_label is not None:\n",
    "        sub_tables[current_label] = (start_col, len(row0) - 1)\n",
    "\n",
    "    result = {}\n",
    "    for label, (sc, ec) in sub_tables.items():\n",
    "        cols_range = list(range(sc, ec + 1))\n",
    "        sub_df = df_raw.iloc[1:, cols_range].copy()\n",
    "\n",
    "        # Drop fully empty columns\n",
    '        sub_df = sub_df.dropna(axis=1, how="all")\n',
    "\n",
    "        if sub_df.empty or sub_df.shape[1] == 0:\n",
    "            continue\n",
    "\n",
    "        # Row 0 of sub_df has replicate headers\n",
    "        header_vals = safe_str_row(sub_df.iloc[0])\n",
    "        sub_data = sub_df.iloc[1:].copy()\n",
    "\n",
    "        # Build column names\n",
    "        new_cols = []\n",
    "        for j, h in enumerate(header_vals):\n",
    '            if j == 0 and ("date" in label.lower() or not h or h in ("nan", "NaT")):\n',
    '                new_cols.append("date")\n',
    '            elif not h or h in ("nan", "NaT"):\n',
    '                new_cols.append(f"col_{j}")\n',
    "            else:\n",
    '                new_cols.append(h.replace(" ", "_"))\n',
    "\n",
    "        sub_data.columns = new_cols\n",
    "        sub_data = sub_data.reset_index(drop=True)\n",
    '        sub_data.insert(0, "experiment", exp_label)\n',
    "\n",
    "        # Clean label for dict key\n",
    '        clean_label = label.replace(" ", "_").replace(".", "").lower()\n',
    "        result[clean_label] = sub_data\n",
    "\n",
    "    return result\n",
    "\n",
    "\n",
    "def parse_harvest(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """\n',
    "    Parse the Harvest measurements sheet.\n",
    "    These sheets contain multiple replicate/treatment sub-tables stacked vertically.\n",
    "    Row pattern: [Replicate-Treatment label], [Column headers], [Data rows], [blank], repeat.\n",
    '    """\n',
    "    all_records = []\n",
    "    current_system = None\n",
    "    header_row = None\n",
    "\n",
    "    # Determine if this is EXP3 format (has 'System' column)\n",
    "    has_system_col = False\n",
    "    for i in range(min(5, len(df_raw))):\n",
    '        row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]\n',
    '        if "System" in row_vals or "System " in row_vals:\n',
    "            has_system_col = True\n",
    "            break\n",
    "\n",
    "    if has_system_col:\n",
    "        # EXP3 format: single table with a 'System' column\n",
    "        for i in range(len(df_raw)):\n",
    '            row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]\n',
    '            if "Plant No." in row_vals or "Plant No" in row_vals:\n',
    "                header_row = i\n",
    "                break\n",
    "\n",
    "        if header_row is not None:\n",
    "            headers = safe_str_row(df_raw.iloc[header_row])\n",
    "            data = df_raw.iloc[header_row + 1:].copy()\n",
    "            data.columns = headers\n",
    '            data = data.dropna(how="all").reset_index(drop=True)\n',
    "\n",
    "            # Forward-fill the System column\n",
    '            if "System " in data.columns:\n',
    '                data = data.rename(columns={"System ": "system"})\n',
    '            elif "System" in data.columns:\n',
    '                data = data.rename(columns={"System": "system"})\n',
    '            if "system" in data.columns:\n',
    '                data["system"] = data["system"].replace("", np.nan).ffill()\n',
    '            data.insert(0, "experiment", exp_label)\n',
    "            return data\n",
    "\n",
    "    # EXP1/EXP2 format: multiple sub-tables separated by replicate headers\n",
    "    i = 0\n",
    "    while i < len(df_raw):\n",
    '        row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]\n',
    "        first_val = row_vals[0]\n",
    "\n",
    "        # Detect replicate/treatment label rows (e.g., 'R1-T1', 'R2-T2')\n",
    '        if first_val and first_val.startswith("R") and "T" in first_val and "Plant" not in first_val:\n',
    "            current_system = first_val\n",
    "            i += 1\n",
    "            continue\n",
    "\n",
    "        # Detect header row\n",
    '        if "Plant No" in first_val or first_val == "Plant No.":\n',
    '            header_row = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]\n',
    "            i += 1\n",
    "            continue\n",
    "\n",
    "        # Skip completely empty rows\n",
    '        if all(v == "" or v == "nan" for v in row_vals):\n',
    "            i += 1\n",
    "            continue\n",
    "\n",
    "        # Data row\n",
    "        if header_row is not None and current_system is not None:\n",
    "            record = dict(zip(header_row, df_raw.iloc[i].tolist()))\n",
    '            record["system"] = current_system\n',
    "            all_records.append(record)\n",
    "\n",
    "        i += 1\n",
    "\n",
    "    if all_records:\n",
    "        result = pd.DataFrame(all_records)\n",
    '        result.insert(0, "experiment", exp_label)\n',
    "        return result\n",
    "\n",
    "    # Fallback: return raw with experiment label\n",
    '    df_raw.insert(0, "experiment", exp_label)\n',
    "    return df_raw\n",
    "\n",
    "\n",
    "def parse_head_diameter(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """\n',
    "    Parse the Head diameter sheet (EXP1 only).\n",
    "    Row 0: day labels; Row 1: replicate label; Row 2: column headers.\n",
    "    Data starts at Row 3. Structure: pairs of (Plant no, Head diameter) per day.\n",
    '    """\n',
    "    # Extract day labels from row 0\n",
    "    day_labels = []\n",
    "    for val in df_raw.iloc[0]:\n",
    '        s = str(val).strip() if pd.notna(val) else ""\n',
    '        if s and s not in ("nan", "NaT"):\n',
    "            day_labels.append(s)\n",
    "\n",
    "    # Identify replicate boundaries from row 1\n",
    "    replicate_rows = []\n",
    "    i = 1\n",
    "    while i < len(df_raw):\n",
    '        first_val = str(df_raw.iloc[i, 0]).strip() if pd.notna(df_raw.iloc[i, 0]) else ""\n',
    '        if first_val.startswith("Replicate") or first_val.startswith("replicate"):\n',
    "            replicate_rows.append((first_val, i))\n",
    "        i += 1\n",
    "\n",
    "    all_records = []\n",
    "\n",
    "    for rep_idx, (rep_label, rep_row) in enumerate(replicate_rows):\n",
    "        data_start = rep_row + 2\n",
    "        if rep_idx + 1 < len(replicate_rows):\n",
    "            data_end = replicate_rows[rep_idx + 1][1]\n",
    "        else:\n",
    "            data_end = len(df_raw)\n",
    "\n",
    "        for row_i in range(data_start, data_end):\n",
    "            row = df_raw.iloc[row_i]\n",
    "            if pd.isna(row.iloc[0]):\n",
    "                continue\n",
    "            for day_idx, day_label in enumerate(day_labels):\n",
    "                col_start = day_idx * 2\n",
    "                if col_start + 1 < len(row):\n",
    "                    record = {\n",
    '                        "experiment": exp_label,\n',
    '                        "replicate": rep_label,\n',
    '                        "day": day_label,\n',
    '                        "plant_no": row.iloc[col_start],\n',
    '                        "head_diameter": row.iloc[col_start + 1],\n',
    "                    }\n",
    "                    all_records.append(record)\n",
    "\n",
    "    return pd.DataFrame(all_records) if all_records else pd.DataFrame()\n",
    "\n",
    "\n",
    "def parse_taste_test(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """Parse Taste Test sheet — preserve as-is with experiment label."""\n',
    "    df = df_raw.copy()\n",
    '    df.insert(0, "experiment", exp_label)\n',
    "    return df\n",
    "\n",
    "\n",
    "def parse_form_responses(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:\n",
    '    """Parse Form Responses sheet — preserve as-is with experiment label."""\n',
    "    df = df_raw.copy()\n",
    '    df.insert(0, "experiment", exp_label)\n',
    "    return df\n",
    "\n",
    "\n",
    'logger.info("Sheet parser functions defined.")'
]))

# ---- Route and parse ----
cells.append(code([
    "# ==========================================================================\n",
    "# Route each sheet to its parser based on sheet name patterns\n",
    "# ==========================================================================\n",
    "\n",
    "def classify_and_parse_sheet(\n",
    "    sheet_name: str, df_raw: pd.DataFrame, exp_label: str\n",
    ") -> Tuple[str, Any]:\n",
    '    """\n',
    "    Classify a sheet by its name and dispatch to the appropriate parser.\n",
    "    Returns (category, parsed_result) where parsed_result is a DataFrame\n",
    "    or dict of DataFrames.\n",
    '    """\n',
    "    sn = sheet_name.lower().strip()\n",
    "\n",
    '    if "seedling" in sn:\n',
    '        return "seedlings", parse_seedlings(df_raw, exp_label)\n',
    '    elif "senso" in sn or "sensor" in sn:\n',
    '        return "sensor_water_quality", parse_sensor_water_quality(df_raw, exp_label)\n',
    '    elif "portabl" in sn:\n',
    '        return "portable_water_quality", parse_portable_water_quality(df_raw, exp_label)\n',
    '    elif "nutrient" in sn:\n',
    '        return "nutrients", parse_nutrients_water(df_raw, exp_label)\n',
    '    elif "harvest" in sn:\n',
    '        return "harvest", parse_harvest(df_raw, exp_label)\n',
    '    elif "head" in sn and "diameter" in sn:\n',
    '        return "head_diameter", parse_head_diameter(df_raw, exp_label)\n',
    '    elif "taste" in sn or "test taste" in sn:\n',
    '        return "taste_test", parse_taste_test(df_raw, exp_label)\n',
    '    elif "form" in sn or "response" in sn:\n',
    '        return "form_responses", parse_form_responses(df_raw, exp_label)\n',
    "    else:\n",
    "        logger.warning(f\"Unknown sheet type: '{sheet_name}' — preserving raw.\")\n",
    '        df_raw.insert(0, "experiment", exp_label)\n',
    '        return "unknown", df_raw\n',
    "\n",
    "\n",
    "# ==========================================================================\n",
    "# Parse all experiments\n",
    "# ==========================================================================\n",
    "parsed_data: Dict[str, Dict[str, Any]] = {}\n",
    "\n",
    "for exp_label, sheets in experiments_raw.items():\n",
    '    logger.info(f"Parsing {exp_label}...")\n',
    "    parsed_data[exp_label] = {}\n",
    "    for sheet_name, df_raw in sheets.items():\n",
    "        category, result = classify_and_parse_sheet(sheet_name, df_raw.copy(), exp_label)\n",
    "\n",
    "        # Nutrients parser returns a dict of sub-tables\n",
    "        if isinstance(result, dict):\n",
    "            for sub_key, sub_df in result.items():\n",
    '                full_key = f"{category}_{sub_key}"\n',
    "                parsed_data[exp_label][full_key] = sub_df\n",
    '                logger.info(f"  ✓ {full_key}: {sub_df.shape}")\n',
    "        else:\n",
    "            parsed_data[exp_label][category] = result\n",
    "            if isinstance(result, pd.DataFrame):\n",
    '                logger.info(f"  ✓ {category}: {result.shape}")\n',
    "\n",
    'print("\\n✅ All sheets parsed successfully.")'
]))

# ---- Shape summary ----
cells.append(code([
    "# ==========================================================================\n",
    "# Display parsed data summary per experiment\n",
    "# ==========================================================================\n",
    "\n",
    "def display_shape_summary(label: str, df: pd.DataFrame) -> None:\n",
    '    """Display a formatted shape summary for a DataFrame."""\n',
    '    print(f"  {label:<35s}  →  {df.shape[0]:>6,} rows × {df.shape[1]:>3} cols")\n',
    "\n",
    "\n",
    'print("=" * 70)\n',
    'print("PARSED DATA SUMMARY PER EXPERIMENT")\n',
    'print("=" * 70)\n',
    "\n",
    "for exp_label, tables in parsed_data.items():\n",
    '    print(f"\\n📂 {exp_label}")\n',
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame):\n",
    "            display_shape_summary(tname, tdata)\n",
    "        else:\n",
    '            print(f"  {tname:<35s}  →  (non-DataFrame: {type(tdata).__name__})")'
]))

# ============================================================
# SECTION 4 - Dataset Overview
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 4 · Dataset Overview\n",
    "\n",
    "For each experiment we display shape, head/tail rows, column names, data types, memory usage, and summary statistics."
]))

cells.append(code([
    "def dataset_overview(df: pd.DataFrame, title: str) -> None:\n",
    '    """\n',
    "    Display a comprehensive overview of a DataFrame:\n",
    "    shape, head, tail, columns, dtypes, memory, summary stats.\n",
    '    """\n',
    '    display(Markdown(f"### {title}"))\n',
    "\n",
    "    # Shape\n",
    '    display(Markdown(f"**Shape:** `{df.shape[0]:,}` rows × `{df.shape[1]}` columns"))\n',
    "\n",
    "    # First 5 rows\n",
    '    display(Markdown("**First 5 rows:**"))\n',
    "    display(df.head())\n",
    "\n",
    "    # Last 5 rows\n",
    '    display(Markdown("**Last 5 rows:**"))\n',
    "    display(df.tail())\n",
    "\n",
    "    # Column names and types\n",
    "    col_info = pd.DataFrame({\n",
    '        "Column": df.columns,\n',
    '        "Dtype": df.dtypes.values,\n',
    '        "Non-Null Count": df.notna().sum().values,\n',
    '        "Null Count": df.isna().sum().values,\n',
    "    })\n",
    '    display(Markdown("**Column Names & Data Types:**"))\n',
    "    display(col_info)\n",
    "\n",
    "    # Memory usage\n",
    "    mem_bytes = df.memory_usage(deep=True).sum()\n",
    "    display(Markdown(\n",
    '        f"**Memory Usage:** `{mem_bytes / 1024:.1f}` KB "\n',
    '        f"(`{mem_bytes / (1024**2):.3f}` MB)"\n',
    "    ))\n",
    "\n",
    "    # Summary statistics\n",
    "    numeric_df = df.select_dtypes(include=[np.number])\n",
    "    if not numeric_df.empty:\n",
    '        display(Markdown("**Summary Statistics (numeric columns):**"))\n',
    "        display(numeric_df.describe())\n",
    "    else:\n",
    '        display(Markdown("*No numeric columns to summarize.*"))\n',
    "\n",
    '    print("\\n" + "─" * 70 + "\\n")'
]))

cells.append(code([
    "# Display overview for each parsed table across all experiments\n",
    "for exp_label, tables in parsed_data.items():\n",
    '    display(Markdown(f"## 📂 {exp_label}"))\n',
    '    display(Markdown("---"))\n',
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame) and not tdata.empty:\n",
    '            dataset_overview(tdata, f"{exp_label} — {tname}")'
]))

# ============================================================
# SECTION 5 - Data Quality Assessment
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 5 · Data Quality Assessment\n",
    "\n",
    "We perform a thorough quality audit across **every** parsed table. This section checks for:\n",
    "\n",
    "| Check | Purpose |\n",
    "|---|---|\n",
    "| Missing values | Identify nulls and their distribution |\n",
    "| Duplicate rows | Detect exact row duplicates |\n",
    "| Constant columns | Find zero-variance columns |\n",
    "| Unique value counts | Understand cardinality |\n",
    "| Invalid datatypes | Detect string values in expected numeric columns |\n",
    "| Negative values | Flag suspicious negatives in measurement columns |\n",
    "| Impossible values | Flag physically impossible measurements |\n",
    "| Outliers | Detect statistical outliers (IQR method) — **flag only, never remove** |\n",
    "| Null percentages | Rank columns by missing data severity |"
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Quality assessment utility functions\n",
    "# ==========================================================================\n",
    "\n",
    "def check_missing_values(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """Return a DataFrame summarizing missing values per column."""\n',
    "    missing = df.isnull().sum()\n",
    "    pct = (missing / len(df) * 100).round(2)\n",
    "    result = pd.DataFrame({\n",
    '        "missing_count": missing,\n',
    '        "missing_pct": pct,\n',
    '        "dtype": df.dtypes,\n',
    "    })\n",
    '    return result[result["missing_count"] > 0].sort_values("missing_pct", ascending=False)\n',
    "\n",
    "\n",
    "def check_duplicates(df: pd.DataFrame) -> int:\n",
    '    """Return count of exact duplicate rows."""\n',
    "    return int(df.duplicated().sum())\n",
    "\n",
    "\n",
    "def check_constant_columns(df: pd.DataFrame) -> List[str]:\n",
    '    """Identify columns with only one unique value (excluding NaN)."""\n',
    "    constant_cols = []\n",
    "    for col in df.columns:\n",
    "        n_unique = df[col].dropna().nunique()\n",
    "        if n_unique <= 1:\n",
    "            constant_cols.append(col)\n",
    "    return constant_cols\n",
    "\n",
    "\n",
    "def check_unique_values(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """Return a summary of unique value counts per column."""\n',
    "    return pd.DataFrame({\n",
    '        "unique_count": df.nunique(),\n',
    '        "total_rows": len(df),\n',
    '        "unique_pct": (df.nunique() / len(df) * 100).round(2),\n',
    '        "sample_values": [\n',
    "            str(df[col].dropna().unique()[:5].tolist()) for col in df.columns\n",
    "        ],\n",
    "    })\n",
    "\n",
    "\n",
    "def check_invalid_numeric(\n",
    "    df: pd.DataFrame, expected_numeric_cols: Optional[List[str]] = None\n",
    ") -> Dict[str, List]:\n",
    '    """\n',
    "    Detect non-numeric values in columns that should be numeric.\n",
    "    If expected_numeric_cols is None, checks all object-type columns\n",
    "    for values that look partially numeric.\n",
    '    """\n',
    "    issues = {}\n",
    "    cols_to_check = expected_numeric_cols or [\n",
    "        c for c in df.columns if df[c].dtype == object\n",
    "    ]\n",
    "\n",
    "    for col in cols_to_check:\n",
    "        if col not in df.columns:\n",
    "            continue\n",
    "        non_null = df[col].dropna()\n",
    "        if non_null.empty:\n",
    "            continue\n",
    '        converted = pd.to_numeric(non_null, errors="coerce")\n',
    "        failed_mask = converted.isna() & non_null.notna()\n",
    "        if failed_mask.any():\n",
    "            bad_vals = non_null[failed_mask].unique().tolist()\n",
    "            if len(bad_vals) > 0:\n",
    "                issues[col] = bad_vals[:10]\n",
    "\n",
    "    return issues\n",
    "\n",
    "\n",
    "def check_negative_values(df: pd.DataFrame) -> Dict[str, int]:\n",
    '    """Flag columns with negative values (suspicious for physical measurements)."""\n',
    "    negatives = {}\n",
    "    for col in df.select_dtypes(include=[np.number]).columns:\n",
    "        neg_count = int((df[col] < 0).sum())\n",
    "        if neg_count > 0:\n",
    "            negatives[col] = neg_count\n",
    "    return negatives\n",
    "\n",
    "\n",
    "def check_outliers_iqr(df: pd.DataFrame, factor: float = 1.5) -> pd.DataFrame:\n",
    '    """\n',
    "    Detect outliers using the IQR method.\n",
    "    Returns a summary of outlier counts per numeric column.\n",
    "    NOTE: Outliers are flagged only — never removed.\n",
    '    """\n',
    "    records = []\n",
    "    for col in df.select_dtypes(include=[np.number]).columns:\n",
    "        q1 = df[col].quantile(0.25)\n",
    "        q3 = df[col].quantile(0.75)\n",
    "        iqr = q3 - q1\n",
    "        lower = q1 - factor * iqr\n",
    "        upper = q3 + factor * iqr\n",
    "        outlier_mask = (df[col] < lower) | (df[col] > upper)\n",
    "        n_outliers = int(outlier_mask.sum())\n",
    "        if n_outliers > 0:\n",
    "            records.append({\n",
    '                "column": col,\n',
    '                "q1": round(q1, 4),\n',
    '                "q3": round(q3, 4),\n',
    '                "iqr": round(iqr, 4),\n',
    '                "lower_bound": round(lower, 4),\n',
    '                "upper_bound": round(upper, 4),\n',
    '                "n_outliers": n_outliers,\n',
    '                "pct_outliers": round(n_outliers / len(df) * 100, 2),\n',
    "            })\n",
    "    return pd.DataFrame(records) if records else pd.DataFrame()\n",
    "\n",
    "\n",
    'logger.info("Quality assessment functions defined.")'
]))

cells.append(code([
    "def run_quality_assessment(\n",
    "    df: pd.DataFrame, title: str, show_details: bool = True\n",
    ") -> Dict[str, Any]:\n",
    '    """\n',
    "    Run the complete quality assessment suite on a DataFrame.\n",
    "    Returns a dict of all findings for downstream use.\n",
    '    """\n',
    "    results = {}\n",
    "\n",
    "    if show_details:\n",
    '        display(Markdown(f"### 🔍 {title}"))\n',
    "\n",
    "    # 1. Missing values\n",
    "    missing_df = check_missing_values(df)\n",
    '    results["missing"] = missing_df\n',
    "    if show_details:\n",
    "        if not missing_df.empty:\n",
    '            display(Markdown("**Missing Values:**"))\n',
    "            display(missing_df)\n",
    "        else:\n",
    '            display(Markdown("**Missing Values:** ✅ None detected."))\n',
    "\n",
    "    # 2. Duplicates\n",
    "    dup_count = check_duplicates(df)\n",
    '    results["duplicates"] = dup_count\n',
    "    if show_details:\n",
    "        if dup_count > 0:\n",
    '            display(Markdown(f"**Duplicate Rows:** ⚠️ **{dup_count}** exact duplicates found."))\n',
    "        else:\n",
    '            display(Markdown("**Duplicate Rows:** ✅ None detected."))\n',
    "\n",
    "    # 3. Constant columns\n",
    "    const_cols = check_constant_columns(df)\n",
    '    results["constant_columns"] = const_cols\n',
    "    if show_details:\n",
    "        if const_cols:\n",
    "            display(Markdown(\n",
    "                f\"**Constant Columns:** ⚠️ {len(const_cols)} column(s) with ≤1 unique value: \"\n",
    "                f\"`{'`, `'.join(map(str, const_cols))}`\"\n",
    "            ))\n",
    "        else:\n",
    '            display(Markdown("**Constant Columns:** ✅ None detected."))\n',
    "\n",
    "    # 4. Unique values\n",
    "    unique_df = check_unique_values(df)\n",
    '    results["unique_values"] = unique_df\n',
    "    if show_details:\n",
    '        display(Markdown("**Unique Value Counts:**"))\n',
    "        display(unique_df)\n",
    "\n",
    "    # 5. Invalid numeric values\n",
    "    invalid_numeric = check_invalid_numeric(df)\n",
    '    results["invalid_numeric"] = invalid_numeric\n',
    "    if show_details:\n",
    "        if invalid_numeric:\n",
    '            display(Markdown("**Invalid Numeric Values (non-numeric in expected numeric columns):**"))\n',
    "            for col, vals in invalid_numeric.items():\n",
    '                display(Markdown(f"- `{col}`: `{vals}` ({len(vals)} unique invalid value(s))"))\n',
    "        else:\n",
    '            display(Markdown("**Invalid Numeric Values:** ✅ None detected."))\n',
    "\n",
    "    # 6. Negative values\n",
    "    negatives = check_negative_values(df)\n",
    '    results["negatives"] = negatives\n',
    "    if show_details:\n",
    "        if negatives:\n",
    '            display(Markdown("**Negative Values (suspicious for physical measurements):**"))\n',
    "            for col, count in negatives.items():\n",
    '                display(Markdown(f"- `{col}`: {count} negative value(s)"))\n',
    "        else:\n",
    '            display(Markdown("**Negative Values:** ✅ None detected in numeric columns."))\n',
    "\n",
    "    # 7. Outliers (IQR)\n",
    "    outlier_df = check_outliers_iqr(df)\n",
    '    results["outliers"] = outlier_df\n',
    "    if show_details:\n",
    "        if not outlier_df.empty:\n",
    "            display(Markdown(\n",
    '                "**Outliers (IQR Method, factor=1.5):**  \\\\n"\n',
    '                "> ⚠️ Flagged for review only — **not removed**."\n',
    "            ))\n",
    "            display(outlier_df)\n",
    "        else:\n",
    '            display(Markdown("**Outliers (IQR):** ✅ None detected."))\n',
    "\n",
    "    if show_details:\n",
    '        print("\\n" + "─" * 70 + "\\n")\n',
    "\n",
    "    return results"
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Run quality assessment on ALL parsed tables\n",
    "# ==========================================================================\n",
    "quality_reports: Dict[str, Dict[str, Dict]] = {}\n",
    "\n",
    "for exp_label, tables in parsed_data.items():\n",
    '    display(Markdown(f"## 📂 {exp_label} — Quality Assessment"))\n',
    '    display(Markdown("---"))\n',
    "    quality_reports[exp_label] = {}\n",
    "\n",
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame) and not tdata.empty:\n",
    "            quality_reports[exp_label][tname] = run_quality_assessment(\n",
    '                tdata, f"{exp_label} — {tname}"\n',
    "            )\n",
    "\n",
    'logger.info("Quality assessment complete for all datasets.")'
]))

# ============================================================
# SECTION 6 - Cleaning
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 6 · Cleaning\n",
    "\n",
    "### Cleaning Philosophy\n",
    "\n",
    "We apply **only safe, reversible, non-destructive** transformations:\n",
    "\n",
    "| ✅ Allowed | ❌ Not Allowed |\n",
    "|---|---|\n",
    "| Trim whitespace from strings | Delete rows due to outliers |\n",
    "| Remove exact duplicate rows | Remove suspicious values |\n",
    "| Standardize column names (snake_case) | Fill missing values without justification |\n",
    "| Fix obvious datatype issues | Drop columns with partial data |\n",
    "| Convert date strings to datetime | Impute scientific measurements |\n",
    "| Replace dash/hyphen placeholders with NaN | Modify measurement values |\n",
    "\n",
    "Every cleaning step shows: **reason**, **before**, and **after**."
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Cleaning utility functions\n",
    "# ==========================================================================\n",
    "\n",
    "def standardize_column_names(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """\n',
    "    Standardize column names to lowercase snake_case.\n",
    "    Removes trailing/leading whitespace, replaces spaces and special chars.\n",
    '    """\n',
    "    df = df.copy()\n",
    "    new_cols = []\n",
    "    for col in df.columns:\n",
    "        c = str(col).strip()\n",
    "        c = c.lower()\n",
    '        c = c.replace(" ", "_").replace(".", "").replace("(", "").replace(")", "")\n',
    '        c = c.replace("__", "_").replace("___", "_")\n',
    '        c = c.rstrip("_")\n',
    "        new_cols.append(c)\n",
    "    df.columns = new_cols\n",
    "    return df\n",
    "\n",
    "\n",
    "def trim_string_whitespace(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """\n',
    "    Trim leading/trailing whitespace from all string columns.\n",
    '    """\n',
    "    df = df.copy()\n",
    '    str_cols = df.select_dtypes(include=["object", "string"]).columns\n',
    "    for col in str_cols:\n",
    "        df[col] = df[col].astype(str).str.strip()\n",
    "        # Restore NaN for values that were 'nan' strings\n",
    '        df[col] = df[col].replace({"nan": np.nan, "NaT": np.nan, "": np.nan, "None": np.nan})\n',
    "    return df\n",
    "\n",
    "\n",
    "def replace_dash_placeholders(df: pd.DataFrame) -> pd.DataFrame:\n",
    '    """\n',
    "    Replace dash/hyphen placeholder values with NaN.\n",
    "    These are commonly used in the raw data to indicate no measurement.\n",
    '    """\n',
    "    df = df.copy()\n",
    '    dash_patterns = ["-", "--", "- ", " -", "N/A", "n/a", "NA", "na"]\n',
    "    df = df.replace(dash_patterns, np.nan)\n",
    "    return df\n",
    "\n",
    "\n",
    "def remove_exact_duplicates(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:\n",
    '    """\n',
    "    Remove exact duplicate rows. Returns (cleaned_df, n_removed).\n",
    '    """\n',
    "    n_before = len(df)\n",
    "    df_clean = df.drop_duplicates().reset_index(drop=True)\n",
    "    n_removed = n_before - len(df_clean)\n",
    "    return df_clean, n_removed\n",
    "\n",
    "\n",
    "def remove_fully_empty_rows(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:\n",
    '    """\n',
    "    Remove rows where ALL values (excluding the 'experiment' label column) are NaN.\n",
    "    Returns (cleaned_df, n_removed).\n",
    '    """\n',
    '    non_label_cols = [c for c in df.columns if c != "experiment"]\n',
    "    mask = df[non_label_cols].notna().any(axis=1)\n",
    "    n_removed = int((~mask).sum())\n",
    "    return df[mask].reset_index(drop=True), n_removed\n",
    "\n",
    "\n",
    "def try_convert_dates(df: pd.DataFrame, date_cols: Optional[List[str]] = None) -> pd.DataFrame:\n",
    '    """\n',
    "    Attempt to convert date columns to datetime.\n",
    "    If date_cols is None, auto-detects columns with 'date' in the name.\n",
    '    """\n',
    "    df = df.copy()\n",
    "    if date_cols is None:\n",
    '        date_cols = [c for c in df.columns if "date" in c.lower()]\n',
    "\n",
    "    for col in date_cols:\n",
    "        if col not in df.columns:\n",
    "            continue\n",
    "        if pd.api.types.is_datetime64_any_dtype(df[col]):\n",
    "            continue\n",
    "        try:\n",
    '            df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)\n',
    "            logger.info(f\"  Converted '{col}' to datetime.\")\n",
    "        except Exception as e:\n",
    "            logger.warning(f\"  Could not convert '{col}' to datetime: {e}\")\n",
    "    return df\n",
    "\n",
    "\n",
    "def try_convert_numeric(df: pd.DataFrame, exclude_cols: Optional[List[str]] = None) -> pd.DataFrame:\n",
    '    """\n',
    "    Attempt to convert object columns to numeric where possible.\n",
    "    Columns where conversion fails for >50% of non-null values are left as-is.\n",
    '    """\n',
    "    df = df.copy()\n",
    "    exclude = set(exclude_cols or [])\n",
    '    exclude.update({"experiment", "replicate", "system", "day"})\n',
    "\n",
    '    for col in df.select_dtypes(include=["object"]).columns:\n',
    "        if col in exclude:\n",
    "            continue\n",
    "        non_null = df[col].dropna()\n",
    "        if non_null.empty:\n",
    "            continue\n",
    '        converted = pd.to_numeric(non_null, errors="coerce")\n',
    "        success_rate = converted.notna().sum() / len(non_null)\n",
    "        if success_rate > 0.5:\n",
    '            df[col] = pd.to_numeric(df[col], errors="coerce")\n',
    "            logger.info(\n",
    "                f\"  Converted '{col}' to numeric \"\n",
    "                f\"({success_rate:.0%} success, {(1-success_rate):.0%} coerced to NaN).\"\n",
    "            )\n",
    "    return df\n",
    "\n",
    "\n",
    'logger.info("Cleaning utility functions defined.")'
]))

cells.append(code([
    "def clean_dataframe(\n",
    "    df: pd.DataFrame, table_name: str, exp_label: str\n",
    ") -> pd.DataFrame:\n",
    '    """\n',
    "    Apply the full cleaning pipeline to a single DataFrame.\n",
    "    Documents every step with before/after comparisons.\n",
    '    """\n',
    '    display(Markdown(f"### 🧹 Cleaning: {exp_label} — {table_name}"))\n',
    "\n",
    "    original_shape = df.shape\n",
    "    df_clean = df.copy()\n",
    "\n",
    "    # ── Step 1: Standardize column names ──\n",
    '    display(Markdown("**Step 1: Standardize column names to snake_case**"))\n',
    '    display(Markdown("*Reason:* Consistent naming convention for downstream processing."))\n',
    "    cols_before = list(df_clean.columns)\n",
    "    df_clean = standardize_column_names(df_clean)\n",
    "    cols_after = list(df_clean.columns)\n",
    "\n",
    "    changed = [(b, a) for b, a in zip(cols_before, cols_after) if b != a]\n",
    "    if changed:\n",
    '        rename_df = pd.DataFrame(changed, columns=["Before (Raw)", "After (Snake Case)"])\n',
    "        display(rename_df.head(15))\n",
    "        if len(changed) > 15:\n",
    '            print(f"  ... and {len(changed) - 15} more.")\n',
    "    else:\n",
    '        display(Markdown("*Before:* " + ", ".join([f"`{c}`" for c in cols_before[:5]]) + ("..." if len(cols_before) > 5 else "")))\n',
    '        display(Markdown("*After:* " + ", ".join([f"`{c}`" for c in cols_after[:5]]) + ("..." if len(cols_after) > 5 else "")))\n',
    '        print("  No changes needed.")\n',
    "\n",
    "    # ── Step 2: Trim whitespace ──\n",
    '    display(Markdown("**Step 2: Trim string whitespace**"))\n',
    '    display(Markdown("*Reason:* Remove invisible whitespace that causes false mismatches."))\n',
    "    \n",
    '    str_cols = df_clean.select_dtypes(include=["object", "string"]).columns\n',
    "    trimmed_examples = []\n",
    "    for col in str_cols:\n",
    "        non_null_mask = df_clean[col].notna()\n",
    "        if not non_null_mask.any():\n",
    "            continue\n",
    "        vals_before = df_clean.loc[non_null_mask, col].astype(str)\n",
    "        vals_after = vals_before.str.strip()\n",
    "        diff_mask = vals_before != vals_after\n",
    "        if diff_mask.any():\n",
    "            for val_b, val_a in zip(vals_before[diff_mask].unique(), vals_after[diff_mask].unique()):\n",
    "                trimmed_examples.append((col, repr(val_b), repr(val_a)))\n",
    "                \n",
    "    df_clean = trim_string_whitespace(df_clean)\n",
    "    \n",
    "    if trimmed_examples:\n",
    '        trim_df = pd.DataFrame(trimmed_examples[:15], columns=["Column", "Before (Untrimmed)", "After (Trimmed)"])\n',
    "        display(trim_df)\n",
    "        if len(trimmed_examples) > 15:\n",
    '            print(f"  ... and {len(trimmed_examples) - 15} more whitespace modifications.")\n',
    "    else:\n",
    "        if len(str_cols) > 0:\n",
    "            sample_col = str_cols[0]\n",
    "            sample_val = df_clean[sample_col].dropna().iloc[0] if df_clean[sample_col].dropna().shape[0] > 0 else \"N/A\"\n",
    '            display(Markdown(f"*Before:* `{repr(sample_val)}` (in `{sample_col}`)"))\n',
    '            display(Markdown(f"*After:* `{repr(sample_val)}` (in `{sample_col}`)"))\n',
    '        print("  No leading/trailing whitespace detected.")\n',
    "\n",
    "    # ── Step 3: Replace dash placeholders ──\n",
    '    display(Markdown("**Step 3: Replace dash/placeholder values with NaN**"))\n',
    '    display(Markdown("*Reason:* Dashes (\'-\') and placeholders are used as \'no data\' markers, not valid measurements."))\n',
    "    \n",
    '    dash_patterns = ["-", "--", "- ", " -", "N/A", "n/a", "NA", "na"]\n',
    "    placeholder_changes = []\n",
    "    for col in df_clean.columns:\n",
    "        mask = df_clean[col].isin(dash_patterns)\n",
    "        if mask.any():\n",
    "            found_vals = df_clean.loc[mask, col].unique()\n",
    "            count = mask.sum()\n",
    "            for val in found_vals:\n",
    "                placeholder_changes.append((col, f\"'{val}' (count: {count})\", \"NaN\"))\n",
    "                \n",
    "    null_before = int(df_clean.isnull().sum().sum())\n",
    "    df_clean = replace_dash_placeholders(df_clean)\n",
    "    null_after = int(df_clean.isnull().sum().sum())\n",
    "    new_nulls = null_after - null_before\n",
    "    \n",
    "    if placeholder_changes:\n",
    '        placeholder_df = pd.DataFrame(placeholder_changes, columns=["Column", "Before (Placeholder)", "After (Converted)"])\n',
    "        display(placeholder_df)\n",
    "    else:\n",
    '        display(Markdown(f"*Before:* {null_before:,} NaN values"))\n',
    '        display(Markdown(f"*After:* {null_after:,} NaN values"))\n',
    '        print("  No dash/placeholder values detected.")\n',
    "\n",
    "    # ── Step 4: Remove fully empty rows ──\n",
    '    display(Markdown("**Step 4: Remove fully empty rows**"))\n',
    '    display(Markdown("*Reason:* Rows with no data (all NaN) are structural artifacts from Excel."))\n',
    "    rows_before = len(df_clean)\n",
    "    df_clean, n_empty = remove_fully_empty_rows(df_clean)\n",
    "    \n",
    '    display(Markdown(f"| Metric | Before | After | Removed |"))\n',
    '    display(Markdown(f"|---|---|---|---|"))\n',
    '    display(Markdown(f"| Row Count | {rows_before:,} | {len(df_clean):,} | {n_empty:,} |"))\n',
    "\n",
    "    # ── Step 5: Remove exact duplicates ──\n",
    '    display(Markdown("**Step 5: Remove exact duplicate rows**"))\n',
    '    display(Markdown("*Reason:* Exact duplicates are data entry artifacts, not real observations."))\n',
    "    rows_before = len(df_clean)\n",
    "    df_clean, n_dups = remove_exact_duplicates(df_clean)\n",
    "    \n",
    '    display(Markdown(f"| Metric | Before | After | Removed |"))\n',
    '    display(Markdown(f"|---|---|---|---|"))\n',
    '    display(Markdown(f"| Row Count | {rows_before:,} | {len(df_clean):,} | {n_dups:,} |"))\n',
    "\n",
    "    # ── Step 6: Convert dates ──\n",
    '    display(Markdown("**Step 6: Convert date columns to datetime**"))\n',
    '    display(Markdown("*Reason:* Enable time-series analysis and proper sorting."))\n',
    "    \n",
    '    date_cols = [c for c in df_clean.columns if "date" in c.lower()]\n',
    "    dtypes_before = {col: str(df_clean[col].dtype) for col in date_cols if col in df_clean.columns}\n",
    "    \n",
    "    df_clean = try_convert_dates(df_clean)\n",
    "    \n",
    "    if date_cols:\n",
    "        date_changes = []\n",
    "        for col in date_cols:\n",
    "            if col in df_clean.columns:\n",
    "                date_changes.append((col, dtypes_before.get(col, \"unknown\"), str(df_clean[col].dtype)))\n",
    "        \n",
    '        date_df = pd.DataFrame(date_changes, columns=["Column", "Before (Dtype)", "After (Dtype)"])\n',
    "        display(date_df)\n",
    "    else:\n",
    '        display(Markdown("*Before:* No date columns"))\n',
    '        display(Markdown("*After:* No date columns"))\n',
    '        print("  No date columns detected.")\n',
    "\n",
    "    # ── Step 7: Convert numeric columns ──\n",
    '    display(Markdown("**Step 7: Convert object columns to numeric where appropriate**"))\n',
    '    display(Markdown(\n',
    '        "*Reason:* Some numeric measurements are stored as strings due to Excel parsing. "\n',
    '        "Columns with >50% numeric success rate are converted; non-convertible values become NaN."\n',
    '    ))\n',
    "    text_keep = [c for c in df_clean.columns if \"diameter\" in c.lower() and \"head\" in c.lower()]\n",
    "    \n",
    '    obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]\n',
    "    dtypes_before = {col: str(df_clean[col].dtype) for col in obj_cols}\n",
    "    \n",
    "    df_clean = try_convert_numeric(df_clean, exclude_cols=text_keep)\n",
    "    \n",
    "    numeric_changes = []\n",
    "    for col in obj_cols:\n",
    "        if col in df_clean.columns:\n",
    "            dtype_after = str(df_clean[col].dtype)\n",
    "            numeric_changes.append((col, dtypes_before[col], dtype_after))\n",
    "                \n",
    "    if numeric_changes:\n",
    '        num_df = pd.DataFrame(numeric_changes, columns=["Column", "Before (Dtype)", "After (Dtype)"])\n',
    "        display(num_df)\n",
    "    else:\n",
    '        display(Markdown("*Before:* No object columns to convert"))\n',
    '        display(Markdown("*After:* No object columns to convert"))\n',
    '        print("  No object columns converted to numeric.")\n',
    "\n",
    "    # ── Summary ──\n",
    '    display(Markdown(f"**Cleaning Summary for {table_name}:**"))\n',
    '    print(f"  Original shape: {original_shape}")\n',
    '    print(f"  Cleaned shape:  {df_clean.shape}")\n',
    '    print(f"  Rows removed:   {original_shape[0] - df_clean.shape[0]}")\n',
    '    print("\\n" + "─" * 70 + "\\n")\n',
    "\n",
    "    return df_clean"
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Apply cleaning to ALL parsed tables\n",
    "# ==========================================================================\n",
    "cleaned_data: Dict[str, Dict[str, pd.DataFrame]] = {}\n",
    "\n",
    "for exp_label, tables in parsed_data.items():\n",
    '    display(Markdown(f"## 📂 {exp_label} — Cleaning"))\n',
    '    display(Markdown("---"))\n',
    "    cleaned_data[exp_label] = {}\n",
    "\n",
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame) and not tdata.empty:\n",
    "            cleaned_data[exp_label][tname] = clean_dataframe(\n",
    "                tdata, tname, exp_label\n",
    "            )\n",
    "\n",
    'logger.info("Cleaning complete for all datasets.")\n',
    'print("\\n✅ All datasets cleaned.")'
]))

# ============================================================
# SECTION 7 - Validation
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## 7 · Validation\n",
    "\n",
    "After cleaning, we re-run the **entire quality assessment suite** on the cleaned data to:\n",
    "1. Confirm that cleaning steps had the desired effect.\n",
    "2. Verify no new issues were introduced.\n",
    "3. Document the remaining data quality state.\n",
    "\n",
    "> Any remaining issues flagged here are documented but **not automatically fixed** — they require domain-expert review."
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Post-cleaning validation\n",
    "# ==========================================================================\n",
    "validation_reports: Dict[str, Dict[str, Dict]] = {}\n",
    "\n",
    "for exp_label, tables in cleaned_data.items():\n",
    '    display(Markdown(f"## ✅ {exp_label} — Post-Cleaning Validation"))\n',
    '    display(Markdown("---"))\n',
    "    validation_reports[exp_label] = {}\n",
    "\n",
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame) and not tdata.empty:\n",
    "            validation_reports[exp_label][tname] = run_quality_assessment(\n",
    '                tdata, f"{exp_label} — {tname} (POST-CLEANING)"\n',
    "            )\n",
    "\n",
    'logger.info("Post-cleaning validation complete.")'
]))

cells.append(code([
    "# ==========================================================================\n",
    "# Compare pre- vs. post-cleaning metrics\n",
    "# ==========================================================================\n",
    "\n",
    'display(Markdown("### 📊 Before vs. After Cleaning Comparison"))\n',
    "\n",
    "comparison_records = []\n",
    "for exp_label in quality_reports:\n",
    "    for tname in quality_reports[exp_label]:\n",
    "        pre = quality_reports[exp_label].get(tname, {})\n",
    "        post = validation_reports.get(exp_label, {}).get(tname, {})\n",
    "\n",
    "        if not pre or not post:\n",
    "            continue\n",
    "\n",
    "        orig_table = parsed_data[exp_label].get(tname)\n",
    "        clean_table = cleaned_data[exp_label].get(tname)\n",
    "\n",
    "        orig_rows = orig_table.shape[0] if isinstance(orig_table, pd.DataFrame) else 0\n",
    "        clean_rows = clean_table.shape[0] if isinstance(clean_table, pd.DataFrame) else 0\n",
    "\n",
    '        pre_missing_df = pre.get("missing", pd.DataFrame())\n',
    "        pre_missing = int(pre_missing_df[\"missing_count\"].sum()) if not pre_missing_df.empty else 0\n",
    '        post_missing_df = post.get("missing", pd.DataFrame())\n',
    "        post_missing = int(post_missing_df[\"missing_count\"].sum()) if not post_missing_df.empty else 0\n",
    "\n",
    "        comparison_records.append({\n",
    '            "Experiment": exp_label,\n',
    '            "Table": tname,\n',
    '            "Rows (Before)": orig_rows,\n',
    '            "Rows (After)": clean_rows,\n',
    '            "Rows Removed": orig_rows - clean_rows,\n',
    '            "Duplicates (Before)": pre.get("duplicates", 0),\n',
    '            "Duplicates (After)": post.get("duplicates", 0),\n',
    '            "Total NaN (Before)": pre_missing,\n',
    '            "Total NaN (After)": post_missing,\n',
    "        })\n",
    "\n",
    "if comparison_records:\n",
    "    comparison_df = pd.DataFrame(comparison_records)\n",
    "    display(comparison_df)\n",
    "else:\n",
    '    print("No comparison data available.")'
]))

# ============================================================
# ============================================================
# SECTION 9 - Data Dictionary
# ============================================================
cells.append(md([
    "---\n",
    "\n",
    "## Section 9 - Data Dictionary\n",
    "\n",
    "Automatically generated professional data dictionaries for every cleaned dataset from each experiment. Each dictionary includes metadata about columns, data types, null counts/percentages, unique value counts, sample values, and descriptions."
]))

cells.append(code([
    "KNOWN_DESCRIPTIONS = {\n",
    "    \"experiment\": \"Experiment identifier (Experiment 1, 2, or 3)\",\n",
    "    \"replicate\": \"Replicate/treatment system identifier\",\n",
    "    \"system\": \"Replicate-Treatment system code (e.g., R1T1)\",\n",
    "    \"date\": \"Date of measurement\",\n",
    "    \"date_\": \"Date of measurement\",\n",
    "    \"plant_no\": \"Plant identification number within replicate\",\n",
    "    \"plant_no_\": \"Plant identification number within replicate\",\n",
    "    \"plant_height__cm\": \"Total plant height in centimeters\",\n",
    "    \"plant_height_cm\": \"Total plant height in centimeters\",\n",
    "    \"shoot_length_cm\": \"Shoot (above-root) length in centimeters\",\n",
    "    \"root_length_cm\": \"Root length in centimeters\",\n",
    "    \"head_diameter_cm\": \"Head diameter in centimeters (often W*H format)\",\n",
    "    \"hd_cm\": \"Head diameter in centimeters (often W*H format)\",\n",
    "    \"stem_diameter__cm\": \"Stem diameter in centimeters\",\n",
    "    \"stem_diameter_cm\": \"Stem diameter in centimeters\",\n",
    "    \"total_weight_g\": \"Total plant weight in grams\",\n",
    "    \"shoot_weight_g\": \"Shoot weight in grams\",\n",
    "    \"root_weight_g\": \"Root weight in grams\",\n",
    "    \"root_weight_g_\": \"Root weight in grams\",\n",
    "    \"no_of_leaves\": \"Number of leaves counted\",\n",
    "    \"no_of_leaves_\": \"Number of leaves counted\",\n",
    "    \"noof_leaves_\": \"Number of leaves counted\",\n",
    "    \"ph\": \"pH level of nutrient solution\",\n",
    "    \"ph_\": \"pH level of nutrient solution\",\n",
    "    \"ec\": \"Electrical conductivity (mS/cm)\",\n",
    "    \"ec_\": \"Electrical conductivity (mS/cm)\",\n",
    "    \"tds\": \"Total dissolved solids (ppm)\",\n",
    "    \"tds_\": \"Total dissolved solids (ppm)\",\n",
    "    \"water_temp\": \"Water temperature (°C)\",\n",
    "    \"water_temp_\": \"Water temperature (°C)\",\n",
    "    \"air_temp\": \"Air temperature (°C)\",\n",
    "    \"air_temp_\": \"Air temperature (°C)\",\n",
    "    \"air_temp_c\": \"Air temperature (°C)\",\n",
    "    \"rh%\": \"Relative humidity percentage\",\n",
    "    \"rh_\": \"Relative humidity percentage\",\n",
    "    \"rh_%\": \"Relative humidity percentage\",\n",
    "    \"co2\": \"CO₂ concentration\",\n",
    "    \"co2_\": \"CO₂ concentration\",\n",
    "    \"co2_ppm\": \"CO₂ concentration in parts per million\",\n",
    "    \"tme\": \"Time of measurement\",\n",
    "    \"tme_\": \"Time of measurement\",\n",
    "    \"day\": \"Day of measurement relative to transplant\",\n",
    "    \"head_diameter\": \"Head diameter (often W*H format)\",\n",
    "    \"shoot_weight_before_removing_wilted_leaves_g\": \"Shoot weight before removing wilted leaves (g)\",\n",
    "    \"shoot_weight_after_removing_wilted_leavesg\": \"Shoot weight after removing wilted leaves (g)\",\n",
    "    \"shoot_weight_before_removing_wilted_leaves_g_\": \"Shoot weight before removing wilted leaves (g)\",\n",
    "    \"shoot_weight_after_removing_wilted_leaves_g_\": \"Shoot weight after removing wilted leaves (g)\",\n",
    "}\n",
    "\n",
    "def generate_data_dictionary(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"Generate a professional data dictionary for a DataFrame.\"\"\"\n",
    "    records = []\n",
    "    for col in df.columns:\n",
    "        col_lower = col.lower().replace(\" \", \"_\")\n",
    "        description = KNOWN_DESCRIPTIONS.get(col_lower, KNOWN_DESCRIPTIONS.get(col, \"\"))\n",
    "        \n",
    "        records.append({\n",
    "            \"Column Name\": col,\n",
    "            \"Data Type\": str(df[col].dtype),\n",
    "            \"Missing Count\": int(df[col].isna().sum()),\n",
    "            \"Missing Percentage\": round(df[col].isna().mean() * 100, 2),\n",
    "            \"Unique Values\": int(df[col].nunique()),\n",
    "            \"Sample Values\": str(df[col].dropna().unique()[:5].tolist()),\n",
    "            \"Description\": description if description else \"\"\n",
    "        })\n",
    "    return pd.DataFrame(records)\n",
    "\n",
    "# Create reports/data_dictionary/ directory\n",
    "dict_dir = PROJECT_ROOT / \"reports\" / \"data_dictionary\"\n",
    "dict_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Generate, display, and save data dictionaries\n",
    "for exp_label, tables in cleaned_data.items():\n",
    "    exp_idx = exp_label.split()[-1]\n",
    "    display(Markdown(f\"### 📂 {exp_label} — Data Dictionaries\"))\n",
    "    \n",
    "    for tname, tdata in tables.items():\n",
    "        if isinstance(tdata, pd.DataFrame) and not tdata.empty:\n",
    "            dd_df = generate_data_dictionary(tdata)\n",
    "            \n",
    "            # Display\n",
    "            display(Markdown(f\"#### {exp_label} — {tname}\"))\n",
    "            display(dd_df)\n",
    "            print()\n",
    "            \n",
    "            # Save\n",
    "            csv_path = dict_dir / f\"exp{exp_idx}_{tname}_dict.csv\"\n",
    "            dd_df.to_csv(csv_path, index=False)\n",
    "            logger.info(f\"Saved data dictionary to: {csv_path}\")\n",
    "\n",
    "print(\"\\n✅ All data dictionaries generated and saved.\")"
]))

# ============================================================
# Build notebook
# ============================================================
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

output_path = "01_Data_Understanding_and_Cleaning.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[OK] Notebook generated: {output_path}")
print(f"   Cells: {len(cells)}")
print(f"   Code cells: {sum(1 for c in cells if c['cell_type'] == 'code')}")
print(f"   Markdown cells: {sum(1 for c in cells if c['cell_type'] == 'markdown')}")
