apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hydrogrow-postgres
  namespace: default
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: hydrogrow-postgres
  template:
    metadata:
      labels:
        app: hydrogrow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "hydrogrow_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: hydrogrow-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hydrogrow-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: default
spec:
  ports:
  - port: 5432
  selector:
    app: hydrogrow-postgres
