"""Add Phase 13 Cloud IoT and MLOps tables

Revision ID: 01a175af9a42
Revises: 3bb94e94424d
Create Date: 2026-07-18 17:43:06.927511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a175af9a42'
down_revision: Union[str, Sequence[str], None] = '3bb94e94424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_deployment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('deployment_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('health_check', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_deployment_logs_created_at'), 'cloud_deployment_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_cloud_deployment_logs_id'), 'cloud_deployment_logs', ['id'], unique=False)
    op.create_table('device_telemetry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('sensor_data', sa.JSON(), nullable=False),
    sa.Column('received_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_telemetry_logs_device_id'), 'device_telemetry_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_telemetry_logs_id'), 'device_telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_device_telemetry_logs_received_timestamp'), 'device_telemetry_logs', ['received_timestamp'], unique=False)
    op.create_table('iot_device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_device_credentials_created_at'), 'iot_device_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_iot_device_credentials_device_id'), 'iot_device_credentials', ['device_id'], unique=True)
    op.create_index(op.f('ix_iot_device_credentials_id'), 'iot_device_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_iot_device_credentials_user_id'), 'iot_device_credentials', ['user_id'], unique=False)
    op.create_table('ml_training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_training_jobs_id'), 'ml_training_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ml_training_jobs_started_at'), 'ml_training_jobs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_jobs_started_at'), table_name='ml_training_jobs')
    op.drop_index(op.f('ix_ml_training_jobs_id'), table_name='ml_training_jobs')
    op.drop_table('ml_training_jobs')
    op.drop_index(op.f('ix_iot_device_credentials_user_id'), table_name='iot_device_credentials')
    op.drop_index(op.f('ix_iot_device_credentials_id'), table_name='iot_device_credentials')
    op.drop_index(op.f('ix_iot_device_credentials_device_id'), table_name='iot_device_credentials')
    op.drop_index(op.f('ix_iot_device_credentials_created_at'), table_name='iot_device_credentials')
    op.drop_table('iot_device_credentials')
    op.drop_index(op.f('ix_device_telemetry_logs_received_timestamp'), table_name='device_telemetry_logs')
    op.drop_index(op.f('ix_device_telemetry_logs_id'), table_name='device_telemetry_logs')
    op.drop_index(op.f('ix_device_telemetry_logs_device_id'), table_name='device_telemetry_logs')
    op.drop_table('device_telemetry_logs')
    op.drop_index(op.f('ix_cloud_deployment_logs_id'), table_name='cloud_deployment_logs')
    op.drop_index(op.f('ix_cloud_deployment_logs_created_at'), table_name='cloud_deployment_logs')
    op.drop_table('cloud_deployment_logs')
    # ### end Alembic commands ###
