"""Add ML model management tables

Revision ID: 3bb94e94424d
Revises: c0ed9d7f8a38
Create Date: 2026-07-18 14:53:07.310733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb94e94424d'
down_revision: Union[str, Sequence[str], None] = 'c0ed9d7f8a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('training_dataset', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_created_at'), 'ml_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_table('training_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_datasets_created_at'), 'training_datasets', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_datasets_id'), 'training_datasets', ['id'], unique=False)
    op.create_table('model_prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('prediction_output', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('inference_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_prediction_logs_created_at'), 'model_prediction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_prediction_logs_id'), 'model_prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_model_prediction_logs_model_id'), 'model_prediction_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_prediction_logs_user_id'), 'model_prediction_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_prediction_logs_user_id'), table_name='model_prediction_logs')
    op.drop_index(op.f('ix_model_prediction_logs_model_id'), table_name='model_prediction_logs')
    op.drop_index(op.f('ix_model_prediction_logs_id'), table_name='model_prediction_logs')
    op.drop_index(op.f('ix_model_prediction_logs_created_at'), table_name='model_prediction_logs')
    op.drop_table('model_prediction_logs')
    op.drop_index(op.f('ix_training_datasets_id'), table_name='training_datasets')
    op.drop_index(op.f('ix_training_datasets_created_at'), table_name='training_datasets')
    op.drop_table('training_datasets')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_created_at'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
