"""Add computer vision plant health tables

Revision ID: 508e6d2fddcc
Revises: 55a1a8e166be
Create Date: 2026-07-18 02:53:37.227842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508e6d2fddcc'
down_revision: Union[str, Sequence[str], None] = '55a1a8e166be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('growth_stage', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_images_id'), 'plant_images', ['id'], unique=False)
    op.create_index(op.f('ix_plant_images_uploaded_at'), 'plant_images', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_plant_images_user_id'), 'plant_images', ['user_id'], unique=False)
    op.create_table('growth_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('height_estimate', sa.Float(), nullable=False),
    sa.Column('leaf_area_estimate', sa.Float(), nullable=False),
    sa.Column('growth_stage', sa.String(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['plant_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_observations_created_at'), 'growth_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_growth_observations_id'), 'growth_observations', ['id'], unique=False)
    op.create_index(op.f('ix_growth_observations_image_id'), 'growth_observations', ['image_id'], unique=False)
    op.create_index(op.f('ix_growth_observations_user_id'), 'growth_observations', ['user_id'], unique=False)
    op.create_table('plant_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('nutrient_status', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['plant_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_analyses_created_at'), 'plant_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_plant_analyses_id'), 'plant_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_plant_analyses_image_id'), 'plant_analyses', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_analyses_image_id'), table_name='plant_analyses')
    op.drop_index(op.f('ix_plant_analyses_id'), table_name='plant_analyses')
    op.drop_index(op.f('ix_plant_analyses_created_at'), table_name='plant_analyses')
    op.drop_table('plant_analyses')
    op.drop_index(op.f('ix_growth_observations_user_id'), table_name='growth_observations')
    op.drop_index(op.f('ix_growth_observations_image_id'), table_name='growth_observations')
    op.drop_index(op.f('ix_growth_observations_id'), table_name='growth_observations')
    op.drop_index(op.f('ix_growth_observations_created_at'), table_name='growth_observations')
    op.drop_table('growth_observations')
    op.drop_index(op.f('ix_plant_images_user_id'), table_name='plant_images')
    op.drop_index(op.f('ix_plant_images_uploaded_at'), table_name='plant_images')
    op.drop_index(op.f('ix_plant_images_id'), table_name='plant_images')
    op.drop_table('plant_images')
    # ### end Alembic commands ###
