"""Add smart automation tables

Revision ID: 55a1a8e166be
Revises: 53319901a49d
Create Date: 2026-07-18 02:42:32.692662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a1a8e166be'
down_revision: Union[str, Sequence[str], None] = '53319901a49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_value', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_automation_rules_user_id'), 'automation_rules', ['user_id'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('expected_harvest_date', sa.DateTime(), nullable=False),
    sa.Column('growth_progress', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_id'), 'crop_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_user_id'), 'crop_cycles', ['user_id'], unique=False)
    op.create_table('automation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('sensor_reading_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_reading_id'], ['sensor_readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_events_created_at'), 'automation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_events_id'), 'automation_events', ['id'], unique=False)
    op.create_index(op.f('ix_automation_events_rule_id'), 'automation_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_automation_events_sensor_reading_id'), 'automation_events', ['sensor_reading_id'], unique=False)
    op.create_index(op.f('ix_automation_events_user_id'), 'automation_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_events_user_id'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_sensor_reading_id'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_rule_id'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_id'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_created_at'), table_name='automation_events')
    op.drop_table('automation_events')
    op.drop_index(op.f('ix_crop_cycles_user_id'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_automation_rules_user_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
