"""Add conversation metadata columns

Revision ID: 5e27e8e9aa1c
Revises: a1476b6cd66b
Create Date: 2026-07-17 15:49:50.126355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e27e8e9aa1c'
down_revision: Union[str, Sequence[str], None] = 'a1476b6cd66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_summary', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('last_message_time', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('message_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'message_count')
    op.drop_column('conversations', 'last_message_time')
    op.drop_column('conversations', 'conversation_summary')
    # ### end Alembic commands ###
