"""Add global agriculture intelligence tables

Revision ID: 612b58afa5d5
Revises: b81be6fe9582
Create Date: 2026-07-18 18:51:56.768700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612b58afa5d5'
down_revision: Union[str, Sequence[str], None] = 'b81be6fe9582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('price_prediction', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trends_created_at'), 'market_trends', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_trends_crop_name'), 'market_trends', ['crop_name'], unique=False)
    op.create_index(op.f('ix_market_trends_id'), 'market_trends', ['id'], unique=False)
    op.create_table('crop_profit_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('production_cost', sa.Float(), nullable=False),
    sa.Column('estimated_income', sa.Float(), nullable=False),
    sa.Column('profit_margin', sa.Float(), nullable=False),
    sa.Column('market_demand_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_profit_analyses_created_at'), 'crop_profit_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_crop_profit_analyses_farm_id'), 'crop_profit_analyses', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_profit_analyses_id'), 'crop_profit_analyses', ['id'], unique=False)
    op.create_table('farm_intelligence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Float(), nullable=False),
    sa.Column('sustainability_score', sa.Float(), nullable=False),
    sa.Column('automation_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_intelligence_scores_farm_id'), 'farm_intelligence_scores', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_intelligence_scores_generated_at'), 'farm_intelligence_scores', ['generated_at'], unique=False)
    op.create_index(op.f('ix_farm_intelligence_scores_id'), 'farm_intelligence_scores', ['id'], unique=False)
    op.create_table('farm_strategy_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('expected_impact', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_strategy_plans_created_at'), 'farm_strategy_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_strategy_plans_farm_id'), 'farm_strategy_plans', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_strategy_plans_id'), 'farm_strategy_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_strategy_plans_id'), table_name='farm_strategy_plans')
    op.drop_index(op.f('ix_farm_strategy_plans_farm_id'), table_name='farm_strategy_plans')
    op.drop_index(op.f('ix_farm_strategy_plans_created_at'), table_name='farm_strategy_plans')
    op.drop_table('farm_strategy_plans')
    op.drop_index(op.f('ix_farm_intelligence_scores_id'), table_name='farm_intelligence_scores')
    op.drop_index(op.f('ix_farm_intelligence_scores_generated_at'), table_name='farm_intelligence_scores')
    op.drop_index(op.f('ix_farm_intelligence_scores_farm_id'), table_name='farm_intelligence_scores')
    op.drop_table('farm_intelligence_scores')
    op.drop_index(op.f('ix_crop_profit_analyses_id'), table_name='crop_profit_analyses')
    op.drop_index(op.f('ix_crop_profit_analyses_farm_id'), table_name='crop_profit_analyses')
    op.drop_index(op.f('ix_crop_profit_analyses_created_at'), table_name='crop_profit_analyses')
    op.drop_table('crop_profit_analyses')
    op.drop_index(op.f('ix_market_trends_id'), table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_crop_name'), table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_created_at'), table_name='market_trends')
    op.drop_table('market_trends')
    # ### end Alembic commands ###
