"""Add multi farm SaaS architecture

Revision ID: 86ee5a85c665
Revises: 01a175af9a42
Create Date: 2026-07-18 17:54:27.276083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ee5a85c665'
down_revision: Union[str, Sequence[str], None] = '01a175af9a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('growth_duration', sa.Integer(), nullable=False),
    sa.Column('optimal_temperature', sa.Float(), nullable=False),
    sa.Column('optimal_ph', sa.Float(), nullable=False),
    sa.Column('optimal_ec', sa.Float(), nullable=False),
    sa.Column('nutrient_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_templates_created_at'), 'crop_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_crop_templates_id'), 'crop_templates', ['id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('farm_size', sa.Float(), nullable=False),
    sa.Column('farm_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_created_at'), 'farms', ['created_at'], unique=False)
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_created_at'), 'knowledge_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_table('farm_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_activity_logs_farm_id'), 'farm_activity_logs', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_activity_logs_id'), 'farm_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_farm_activity_logs_timestamp'), 'farm_activity_logs', ['timestamp'], unique=False)
    op.create_table('farm_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_members_farm_id'), 'farm_members', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_members_id'), 'farm_members', ['id'], unique=False)
    op.create_index(op.f('ix_farm_members_joined_at'), 'farm_members', ['joined_at'], unique=False)
    op.create_index(op.f('ix_farm_members_user_id'), 'farm_members', ['user_id'], unique=False)
    op.create_table('farm_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_subscriptions_created_at'), 'farm_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_subscriptions_farm_id'), 'farm_subscriptions', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_subscriptions_id'), 'farm_subscriptions', ['id'], unique=False)
    op.create_table('greenhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_size', sa.Float(), nullable=False),
    sa.Column('environment_type', sa.String(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_greenhouses_created_at'), 'greenhouses', ['created_at'], unique=False)
    op.create_index(op.f('ix_greenhouses_farm_id'), 'greenhouses', ['farm_id'], unique=False)
    op.create_index(op.f('ix_greenhouses_id'), 'greenhouses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_greenhouses_id'), table_name='greenhouses')
    op.drop_index(op.f('ix_greenhouses_farm_id'), table_name='greenhouses')
    op.drop_index(op.f('ix_greenhouses_created_at'), table_name='greenhouses')
    op.drop_table('greenhouses')
    op.drop_index(op.f('ix_farm_subscriptions_id'), table_name='farm_subscriptions')
    op.drop_index(op.f('ix_farm_subscriptions_farm_id'), table_name='farm_subscriptions')
    op.drop_index(op.f('ix_farm_subscriptions_created_at'), table_name='farm_subscriptions')
    op.drop_table('farm_subscriptions')
    op.drop_index(op.f('ix_farm_members_user_id'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_joined_at'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_id'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_farm_id'), table_name='farm_members')
    op.drop_table('farm_members')
    op.drop_index(op.f('ix_farm_activity_logs_timestamp'), table_name='farm_activity_logs')
    op.drop_index(op.f('ix_farm_activity_logs_id'), table_name='farm_activity_logs')
    op.drop_index(op.f('ix_farm_activity_logs_farm_id'), table_name='farm_activity_logs')
    op.drop_table('farm_activity_logs')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_created_at'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_created_at'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_crop_templates_id'), table_name='crop_templates')
    op.drop_index(op.f('ix_crop_templates_created_at'), table_name='crop_templates')
    op.drop_table('crop_templates')
    # ### end Alembic commands ###
