"""Add digital twin simulation tables

Revision ID: ad43e4eea369
Revises: 508e6d2fddcc
Create Date: 2026-07-18 03:02:02.939011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad43e4eea369'
down_revision: Union[str, Sequence[str], None] = '508e6d2fddcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_twin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('system_type', sa.String(), nullable=False),
    sa.Column('area_size', sa.Float(), nullable=False),
    sa.Column('lighting_setup', sa.String(), nullable=False),
    sa.Column('nutrient_system', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_twin_profiles_created_at'), 'digital_twin_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_digital_twin_profiles_id'), 'digital_twin_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_digital_twin_profiles_user_id'), 'digital_twin_profiles', ['user_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('initial_conditions', sa.JSON(), nullable=False),
    sa.Column('final_prediction', sa.JSON(), nullable=False),
    sa.Column('yield_change_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['digital_twin_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_created_at'), 'simulation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_profile_id'), 'simulation_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_user_id'), 'simulation_runs', ['user_id'], unique=False)
    op.create_table('growth_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('predicted_height', sa.Float(), nullable=False),
    sa.Column('predicted_weight', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('growth_stage', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_forecasts_created_at'), 'growth_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_growth_forecasts_id'), 'growth_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_growth_forecasts_simulation_id'), 'growth_forecasts', ['simulation_id'], unique=False)
    op.create_table('simulation_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('modified_value', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_parameters_id'), 'simulation_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_parameters_simulation_id'), 'simulation_parameters', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_parameters_simulation_id'), table_name='simulation_parameters')
    op.drop_index(op.f('ix_simulation_parameters_id'), table_name='simulation_parameters')
    op.drop_table('simulation_parameters')
    op.drop_index(op.f('ix_growth_forecasts_simulation_id'), table_name='growth_forecasts')
    op.drop_index(op.f('ix_growth_forecasts_id'), table_name='growth_forecasts')
    op.drop_index(op.f('ix_growth_forecasts_created_at'), table_name='growth_forecasts')
    op.drop_table('growth_forecasts')
    op.drop_index(op.f('ix_simulation_runs_user_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_profile_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_created_at'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_digital_twin_profiles_user_id'), table_name='digital_twin_profiles')
    op.drop_index(op.f('ix_digital_twin_profiles_id'), table_name='digital_twin_profiles')
    op.drop_index(op.f('ix_digital_twin_profiles_created_at'), table_name='digital_twin_profiles')
    op.drop_table('digital_twin_profiles')
    # ### end Alembic commands ###
