"""Add agriculture marketplace and community ecosystem

Revision ID: b81be6fe9582
Revises: 86ee5a85c665
Create Date: 2026-07-18 18:41:10.104485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81be6fe9582'
down_revision: Union[str, Sequence[str], None] = '86ee5a85c665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_template_libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=False),
    sa.Column('nutrient_profile', sa.JSON(), nullable=False),
    sa.Column('environmental_profile', sa.JSON(), nullable=False),
    sa.Column('growth_duration', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_template_libraries_created_at'), 'crop_template_libraries', ['created_at'], unique=False)
    op.create_index(op.f('ix_crop_template_libraries_creator_id'), 'crop_template_libraries', ['creator_id'], unique=False)
    op.create_index(op.f('ix_crop_template_libraries_id'), 'crop_template_libraries', ['id'], unique=False)
    op.create_table('expert_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expertise_area', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('certification', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_profiles_created_at'), 'expert_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_expert_profiles_id'), 'expert_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_expert_profiles_user_id'), 'expert_profiles', ['user_id'], unique=False)
    op.create_table('expert_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_recommendations_created_at'), 'expert_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_expert_recommendations_id'), 'expert_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_expert_recommendations_user_id'), 'expert_recommendations', ['user_id'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_created_at'), 'marketplace_products', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_products_id'), 'marketplace_products', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_seller_id'), 'marketplace_products', ['seller_id'], unique=False)
    op.create_table('farmer_communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_communities_created_at'), 'farmer_communities', ['created_at'], unique=False)
    op.create_index(op.f('ix_farmer_communities_created_by'), 'farmer_communities', ['created_by'], unique=False)
    op.create_index(op.f('ix_farmer_communities_farm_id'), 'farmer_communities', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farmer_communities_id'), 'farmer_communities', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['farmer_communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_farmer_communities_id'), table_name='farmer_communities')
    op.drop_index(op.f('ix_farmer_communities_farm_id'), table_name='farmer_communities')
    op.drop_index(op.f('ix_farmer_communities_created_by'), table_name='farmer_communities')
    op.drop_index(op.f('ix_farmer_communities_created_at'), table_name='farmer_communities')
    op.drop_table('farmer_communities')
    op.drop_index(op.f('ix_marketplace_products_seller_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_created_at'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_expert_recommendations_user_id'), table_name='expert_recommendations')
    op.drop_index(op.f('ix_expert_recommendations_id'), table_name='expert_recommendations')
    op.drop_index(op.f('ix_expert_recommendations_created_at'), table_name='expert_recommendations')
    op.drop_table('expert_recommendations')
    op.drop_index(op.f('ix_expert_profiles_user_id'), table_name='expert_profiles')
    op.drop_index(op.f('ix_expert_profiles_id'), table_name='expert_profiles')
    op.drop_index(op.f('ix_expert_profiles_created_at'), table_name='expert_profiles')
    op.drop_table('expert_profiles')
    op.drop_index(op.f('ix_crop_template_libraries_id'), table_name='crop_template_libraries')
    op.drop_index(op.f('ix_crop_template_libraries_creator_id'), table_name='crop_template_libraries')
    op.drop_index(op.f('ix_crop_template_libraries_created_at'), table_name='crop_template_libraries')
    op.drop_table('crop_template_libraries')
    # ### end Alembic commands ###
