"""Add autonomous AI decision tables

Revision ID: c0ed9d7f8a38
Revises: ad43e4eea369
Create Date: 2026-07-18 12:50:15.416785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ed9d7f8a38'
down_revision: Union[str, Sequence[str], None] = 'ad43e4eea369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output_result', sa.JSON(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_logs_created_at'), 'agent_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_user_id'), 'agent_execution_logs', ['user_id'], unique=False)
    op.create_table('farm_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('analysis', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_decisions_created_at'), 'farm_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_decisions_id'), 'farm_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_farm_decisions_user_id'), 'farm_decisions', ['user_id'], unique=False)
    op.create_table('recommendation_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['farm_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_histories_created_at'), 'recommendation_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_decision_id'), 'recommendation_histories', ['decision_id'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_id'), 'recommendation_histories', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_user_id'), 'recommendation_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_histories_user_id'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_id'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_decision_id'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_created_at'), table_name='recommendation_histories')
    op.drop_table('recommendation_histories')
    op.drop_index(op.f('ix_farm_decisions_user_id'), table_name='farm_decisions')
    op.drop_index(op.f('ix_farm_decisions_id'), table_name='farm_decisions')
    op.drop_index(op.f('ix_farm_decisions_created_at'), table_name='farm_decisions')
    op.drop_table('farm_decisions')
    op.drop_index(op.f('ix_agent_execution_logs_user_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_created_at'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    # ### end Alembic commands ###
